import Head from "next/head";
import ApiDetails from "../components/ApiDetails";
import Bookings from "../components/Bookings";
import CustomerDetails from "../components/CustomerDetails";
import Header from "../components/Header";
import StatusBar from "../components/StatusBar";

const Home = () => {
  return (
    <div className="bg-[#f5f5fd]">
      <Head>
        <title>API Details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <StatusBar />
      <Bookings />
      <ApiDetails />
      <CustomerDetails />
    </div>
  );
};

export default Home;
